# --- Site Metadata ---
theme: jekyll-theme-chirpy
lang: en
timezone: Etc/UTC

title: win64.li
tagline: Research. Leaks. Write-ups.
description: >-
  Independent exploit development, security research / analysis / techniques
  . .

url: "https://win64.li"
baseurl: ""

github:
  username: win64k

social:
  name: 
  email: 
  links:
    - https://github.com/win64k
    - https://x.com/dulls  # pseudonym drop

theme_mode: dark
avatar: https://github.com/win64k.png

toc: true
paginate: 10

comments:
  provider:

pwa:
  enabled: true
  cache:
    enabled: true

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# In each post frontmatter:
# sensitive: [true | false]
# redacted: [true | false]

exclude:
  - README.md
  - LICENSE
  - "*.config.js"
  - "package*.json"
  - node_modules
  - vendor
  - docs
  - tools

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

webmaster_verifications:
  google:
  bing:

analytics:
  cloudflare:
    id:
