# --- Site Metadata ---
theme: jekyll-theme-chirpy
lang: en
timezone: Etc/UTC

title: win64k 
tagline: Independent exploit development, security research, analysis, and techniques.. 

url: "https://win64.li"
baseurl: ""

github:
  username: win64k

social:
  github: win64k
  twitter: dulls

theme_mode: dark
avatar: https://github.com/win64k.png

toc: true
paginate: 10

comments:
  provider:

pwa:
  enabled: false
  cache:
    enabled: false

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude:
  - README.md
  - LICENSE
  - "*.config.js"
  - "package*.json"
  - node_modules
  - vendor
  - docs
  - tools

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

webmaster_verifications:
  google:
  bing:

analytics:
  cloudflare:
    id:

twitter:
  username: dulls
  card: summary_large_image
