# --- Site Configuration ---

# Import the theme
theme: jekyll-theme-chirpy

# Language & Timezone
lang: en
timezone: Etc/UTC

# --- jekyll-seo-tag settings ---
title: win64.li
tagline: >-
  Independent exploit development, security research, analysis, and techniques.
description: Research. Techniques. Write-ups.
url: "https://win64.li"
baseurl: ""

github:
  username: win64k

twitter:
  username: dulls

social:
  name: rey
  email:
  links:
    - https://x.com/dulls
    - https://github.com/win64k

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# --- Analytics ---
analytics:
  google:
    id:
  cloudflare:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  fathom:
    id:

# Pageviews (optional)
pageviews:
  provider:

# --- Theme Options ---
theme_mode: dark  # [light | dark] or leave blank to follow system preference
cdn:
avatar: "https://github.com/win64k.png"
social_preview_image:
toc: true

comments:
  provider: # [disqus | utterances | giscus]
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# --- Static Assets ---
assets:
  self_host:
    enabled:
    env:

# --- Progressive Web App (PWA) ---
pwa:
  enabled: false
  cache:
    enabled: false
    deny_paths:

# --- Pagination ---
paginate: 10

# --- Markdown / Syntax Highlighting ---
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# --- Collections & Defaults ---
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: rey
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# --- SASS & HTML Compression ---
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# --- Exclusions ---
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# --- Archives for Categories & Tags ---
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
